services:
  server:
    image: $ECR_REGISTRY/x-tracker-be
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - DB_SOURCE=postgresql://root:secret@localhost:5432/xtracker?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
     image: postgres
     restart: always
     user: postgres
#     secrets:
#       - db-password
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=xtracker
       - POSTGRES_PASSWORD=secret
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
volumes:
   db-data:
#secrets:
#   db-password:
#     secretsfile: db/password.txt

