---
- name: Set up EC2 instance for frontend
  hosts: instances
  become: true
  remote_user: admin

  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: true

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      register: result

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
#        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Reset ssh connection to allow user changes to affect ansible user
      meta:
        reset_connection
