// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID            int64     `json:"id"`
	UserID        int64     `json:"user_id"`
	DeviceKey     uuid.UUID `json:"device_key"`
	DeviceName    string    `json:"device_name"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	LastSeen      time.Time `json:"last_seen"`
	DeviceType    string    `json:"device_type"`
	DeviceVersion string    `json:"device_version"`
}

type DeviceActivity struct {
	ID           int64     `json:"id"`
	DeviceID     int64     `json:"device_id"`
	CreatedAt    time.Time `json:"created_at"`
	ActivityType string    `json:"activity_type"`
	ActivityData []byte    `json:"activity_data"`
}

type User struct {
	ID             int64       `json:"id"`
	Username       string      `json:"username"`
	HashedPassword string      `json:"hashed_password"`
	Email          string      `json:"email"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	Status         string      `json:"status"`
	Role           string      `json:"role"`
	PhoneNumber    pgtype.Int8 `json:"phone_number"`
	CountryCode    pgtype.Int4 `json:"country_code"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	PostalCode     pgtype.Text `json:"postal_code"`
}
