// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccess(ctx context.Context, arg CreateAccessParams) (DeviceAccess, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccessWithDeviceID(ctx context.Context, deviceID int64) ([]DeviceAccess, error)
	DeleteAccessWithUserID(ctx context.Context, userID int64) ([]DeviceAccess, error)
	GetAccessWithDeviceID(ctx context.Context, deviceID int64) ([]DeviceAccess, error)
	GetAccessWithDeviceIDAndUserID(ctx context.Context, arg GetAccessWithDeviceIDAndUserIDParams) (DeviceAccess, error)
	GetAccessWithUserID(ctx context.Context, userID int64) ([]DeviceAccess, error)
	GetDevice(ctx context.Context, id int64) (Device, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
